### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by Oreobun** [compphoto/BoostingMonocularDepth#35]
Hi all, I have successfully cloned the repository and run it on my Windows PC a few months ago. I am trying it on my Linux device now but I encounter an HTTP Error. I run using this:
`python run.py --Final --data_dir PATH_TO_INPUT --output_dir PATH_TO_RESULT --depthNet 0`
I created a conda environment with python=3.7 and installed the following:
`conda install pytorch torchvision opencv cudatoolkit=10.2 -c pytorch`
`conda install matplotlib`
`conda install scipy`
`conda install scikit-image`

with the --data_dir and --output_dir inserted and the exact error message I obtained is this:

`initialize network with normal`
`loading the model from ./pix2pix/checkpoints/mergemodel/latest_net_G.pth`
`Loading weights:  midas/model.pt`
`Downloading: "https://github.com/facebookresearch/WSL-Images/archive/master.zip" to` `/home/zhenkai/.cache/torch/hub/master.zip`
`Traceback (most recent call last):`
 ` File "run.py", line 580, in <module>`
  `  run(dataset_, option_)`
  `File "run.py", line 59, in run`
   ` midasmodel = MidasNet(midas_model_path, non_negative=True)`
  `File "/home/zhenkai/boosting_monocular/BoostingMonocularDepth/midas/models/midas_net.py", line 30, in __init__`
   ` self.pretrained, self.scratch = _make_encoder(features, use_pretrained)`
  `File "/home/zhenkai/boosting_monocular/BoostingMonocularDepth/midas/models/blocks.py", line 6, in _make_encoder`
   ` pretrained = _make_pretrained_resnext101_wsl(use_pretrained)`
  `File "/home/zhenkai/boosting_monocular/BoostingMonocularDepth/midas/models/blocks.py", line 26, in` `_make_pretrained_resnext101_wsl`
 `   resnet = torch.hub.load("facebookresearch/WSL-Images", "resnext101_32x8d_wsl")`
  `File "/home/zhenkai/anaconda3/envs/boosting/lib/python3.7/site-packages/torch/hub.py", line 345, in load`
   ` repo_dir = _get_cache_or_reload(github, force_reload, verbose)`
  `File "/home/zhenkai/anaconda3/envs/boosting/lib/python3.7/site-packages/torch/hub.py", line 144, in _get_cache_or_reload`
   ` download_url_to_file(url, cached_file, progress=False)`
  `File "/home/zhenkai/anaconda3/envs/boosting/lib/python3.7/site-packages/torch/hub.py", line 379, in download_url_to_file`
   ` u = urlopen(req)`
  `File "/home/zhenkai/anaconda3/envs/boosting/lib/python3.7/urllib/request.py", line 222, in urlopen`
   ` return opener.open(url, data, timeout)`
  `File "/home/zhenkai/anaconda3/envs/boosting/lib/python3.7/urllib/request.py", line 531, in open`
   ` response = meth(req, response)`
  `File "/home/zhenkai/anaconda3/envs/boosting/lib/python3.7/urllib/request.py", line 641, in http_response`
   ` 'http', request, response, code, msg, hdrs)`
  `File "/home/zhenkai/anaconda3/envs/boosting/lib/python3.7/urllib/request.py", line 563, in error`
   ` result = self._call_chain(*args)`
  `File "/home/zhenkai/anaconda3/envs/boosting/lib/python3.7/urllib/request.py", line 503, in _call_chain`
   ` result = func(*args)`
  `File "/home/zhenkai/anaconda3/envs/boosting/lib/python3.7/urllib/request.py", line 755, in http_error_302`
   ` return self.parent.open(new, timeout=req.timeout)`
  `File "/home/zhenkai/anaconda3/envs/boosting/lib/python3.7/urllib/request.py", line 531, in open`
   ` response = meth(req, response)`
  `File "/home/zhenkai/anaconda3/envs/boosting/lib/python3.7/urllib/request.py", line 641, in http_response`
   ` 'http', request, response, code, msg, hdrs)`
  `File "/home/zhenkai/anaconda3/envs/boosting/lib/python3.7/urllib/request.py", line 569, in error`
   ` return self._call_chain(*args)`
  `File "/home/zhenkai/anaconda3/envs/boosting/lib/python3.7/urllib/request.py", line 503, in _call_chain`
   ` result = func(*args)`
  `File "/home/zhenkai/anaconda3/envs/boosting/lib/python3.7/urllib/request.py", line 649, in http_error_default`
   ` raise HTTPError(req.full_url, code, msg, hdrs, fp)`
`urllib.error.HTTPError: HTTP Error 404: Not Found
`

Feels like the problem lies with `Downloading:"https://github.com/facebookresearch/WSL-Images/archive/master.zip"`. Any help is greatly appreciated. thank you!

Update:  Tried the google collab file as well, it gives a similar error.

**Comment by Oreobun** [comment]
> Hi.
> 
> Thanks for your detailed log @Oreobun. As you said the issue was caused by "facebookresearch/WSL-Images" update. I deployed a fix for the issue.
> 
> Please pull the most recent changes and try it out again. @mahdis-sa Please close the issue if it was also solved for you.

Thank you so much, the problem has been resolved
