### ISSUE TITLE
RuntimeError: The size of tensor a (75) must match the size of tensor b (76) at non-singleton dimension 3

### ISSUE THREAD

**Issue by bhanuteja2001** [compphoto/BoostingMonocularDepth#51]
Not working in my local

**Comment by bhanuteja2001** [comment]
initialize network with normal
loading the model from ./pix2pix/checkpoints/mergemodel\latest_net_G.pth
start processing
processing image 0 : sample1
         wholeImage being processed in : 1792
                 DEBUG| GPU THRESHOLD REACHED 1792 ---> 1200
Traceback (most recent call last):
  File "run.py", line 580, in <module>
    run(dataset_, option_)
  File "run.py", line 125, in run
    whole_estimate = doubleestimate(img, option.net_receptive_field_size, whole_image_optimal_size,
  File "run.py", line 394, in doubleestimate
    estimate2 = singleestimate(img, size2, net_type)
  File "run.py", line 422, in singleestimate
    return estimateleres(img, msize)
  File "run.py", line 520, in estimateleres
    prediction = leresmodel.inference(img_torch)
  File "G:\Fiver\BoostingMonocularDepth\lib\multi_depth_model_woauxi.py", line 18, in inference
    depth = self.depth_model(input)
  File "C:\Users\Bhanu\anaconda3\envs\boost\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "G:\Fiver\BoostingMonocularDepth\lib\multi_depth_model_woauxi.py", line 32, in forward
    out_logit = self.decoder_modules(lateral_out)
  File "C:\Users\Bhanu\anaconda3\envs\boost\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "G:\Fiver\BoostingMonocularDepth\lib\network_auxi.py", line 57, in forward
    x_8 = self.ffm2(features[2], x_16)  # 1/8
  File "C:\Users\Bhanu\anaconda3\envs\boost\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "G:\Fiver\BoostingMonocularDepth\lib\network_auxi.py", line 209, in forward
    x = x + high_x
RuntimeError: The size of tensor a (75) must match the size of tensor b (76) at non-singleton dimension 3

**Comment by bhanuteja2001** [comment]
I have changed the following

whole_size_threshold = 2000  # R_max from the paper
GPU_threshold = 1200 # Limit for the GPU (NVIDIA RTX 2080), can be adjusted

**Comment by bhanuteja2001** [comment]
The code works fine with MiDaS.
The above error occured while using LeReS

**Comment by sebastian-dille** [comment]
Hi @bhanuteja2001,

it looks like the issue is coming from 
`GPU_threshold = 1200`

The network requires a multiple of 32 as input resolution. Try setting the threshold to 1184 or 1216.
