### ISSUE TITLE
Feature Request: Run on CPU or MPS for Apple M1/M2 

### ISSUE THREAD

**Issue by krummrey** [compphoto/BoostingMonocularDepth#59]
I've been trying to get it to run on my M1 machine. Remove CUDA dependencies wherever I found them. But now I'm stuck here:

```
initialize network with normal
loading the model from ./pix2pix/checkpoints/mergemodel/latest_net_G.pth
start processing
processing image 0 : sample1
(2964, 3820, 3)
	 wholeImage being processed in : 2912
 	 	 DEBUG| GPU THRESHOLD REACHED 2912 ---> 1568
Traceback (most recent call last):
  File "run.py", line 581, in <module>
    run(dataset_, option_)
  File "run.py", line 125, in run
    whole_estimate = doubleestimate(img, option.net_receptive_field_size, whole_image_optimal_size,
  File "run.py", line 401, in doubleestimate
    pix2pixmodel.test()
  File "/Users/jan/Documents/ML/BoostingMonocularDepth/pix2pix/models/base_model.py", line 106, in test
    self.forward()
  File "/Users/jan/Documents/ML/BoostingMonocularDepth/pix2pix/models/pix2pix4depth_model.py", line 116, in forward
    self.fake_B = self.netG(self.real_A)  # G(A)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sketch-simplyfication/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/jan/Documents/ML/BoostingMonocularDepth/pix2pix/models/networks.py", line 473, in forward
    return self.model(input)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sketch-simplyfication/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/jan/Documents/ML/BoostingMonocularDepth/pix2pix/models/networks.py", line 541, in forward
    return self.model(x)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sketch-simplyfication/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sketch-simplyfication/lib/python3.8/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sketch-simplyfication/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sketch-simplyfication/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sketch-simplyfication/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (MPSFloatType) and weight type (torch.FloatTensor) should be the same
```

I don't know where to put a `.to("mps")` or whatever needs to be done.
Anyone else got it to work?

**Comment by miangoleh** [comment]
I am not sure if is helpful and I cannot test it our since I don't own a M1/M2 device but here are a few tips:

We define the processing device for the base depth estimation models here:
[depth device](https://github.com/compphoto/BoostingMonocularDepth/blob/95bdf0eee5fff711c38b129f4b7f92b0d8c2cccb/run.py#L32)


And the device for the merging network is defined here:
[mergenet device](https://github.com/compphoto/BoostingMonocularDepth/blob/95bdf0eee5fff711c38b129f4b7f92b0d8c2cccb/pix2pix/models/base_model.py#L35)

Probably you need to change these to 
`   device = torch.device("mps")
`

**Comment by gomezbiggeri** [comment]
@krummrey I'm interested in running it on an M1 as well, did you ever got it to work?

**Comment by krummrey** [comment]
@gomezbiggeri I found [this implementation](https://github.com/thygate/stable-diffusion-webui-depthmap-script) the closest so far. I couldn't get this repo to work with MPS.

**Comment by miangoleh** [comment]
Closing due to inactivity.
