### ISSUE TITLE
Colab error: FileNotFoundError: [Errno 2] No such file or directory: 'res101.pth'

### ISSUE THREAD

**Issue by skabbit** [compphoto/BoostingMonocularDepth#69]
When trying to use Leres, I get the error, here is the log:
```
initialize network with normal
loading the model from ./pix2pix/checkpoints/mergemodel/latest_net_G.pth
Traceback (most recent call last):
  File "/content/BoostingMonocularDepth/run.py", line 580, in <module>
    run(dataset_, option_)
  File "/content/BoostingMonocularDepth/run.py", line 72, in run
    checkpoint = torch.load(leres_model_path)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'res101.pth'
```

Most probably, it is because the link https://cloudstor.aarnet.edu.au/plus/s/lTIJF4vrvHCAI31/download is outdated now (service is not available now: `CloudStor was decommissioned at 12pm AEDT on Friday 15 December 2023.`)

I found this model on HuggingFace, so you can download it like this:
```
!wget https://huggingface.co/lllyasviel/Annotators/resolve/850be791e8f704b2fa2e55ec9cc33a6ae3e28832/res101.pth
```

Don't forget to put file `res101.pth` inside `BoostingMonocularDepth` folder

**Comment by miangoleh** [comment]
Thanks @skabbit! I will incorporate it into our repo.
